import keyMirror from 'keymirror'

export default keyMirror({
  SPEAKER_INDEX_START: null,
  SPEAKER_INDEX_COMPLETE: null,
  SPEAKER_INDEX_FAIL: null,

  SPEAKER_CREATE_START: null,
  SPEAKER_CREATE_COMPLETE: null,
  SPEAKER_CREATE_FAIL: null,

  SPEAKER_SHOW_START: null,
  SPEAKER_SHOW_COMPLETE: null,
  SPEAKER_SHOW_FAIL: null,

  SPEAKER_UPDATE_START: null,
  SPEAKER_UPDATE_COMPLETE: null,
  SPEAKER_UPDATE_FAIL: null,

  SPEAKER_DELETE_START: null,
  SPEAKER_DELETE_COMPLETE: null,
  SPEAKER_DELETE_FAIL: null,

  SPEAKER_COMMENT_UPDATE_START: null,
  SPEAKER_COMMENT_UPDATE_COMPLETE: null,
  SPEAKER_COMMENT_UPDATE_FAIL: null,
})