import keyMirror from 'keymirror'

export default keyMirror({
  CART_INDEX_START: null,
  CART_INDEX_COMPLETE: null,
  CART_INDEX_FAIL: null,

  CART_CREATE_START: null,
  CART_CREATE_COMPLETE: null,
  CART_CREATE_FAIL: null,

  CART_SHOW_START: null,
  CART_SHOW_COMPLETE: null,
  CART_SHOW_FAIL: null,

  CART_UPDATE_START: null,
  CART_UPDATE_COMPLETE: null,
  CART_UPDATE_FAIL: null,

  CART_DELETE_START: null,
  CART_DELETE_COMPLETE: null,
  CART_DELETE_FAIL: null,

  CART_ITEM_CREATE_START: null,
  CART_ITEM_CREATE_COMPLETE: null,
  CART_ITEM_CREATE_FAIL: null,

  CART_ITEM_SHOW_START: null,
  CART_ITEM_SHOW_COMPLETE: null,
  CART_ITEM_SHOW_FAIL: null,

  CART_ITEM_UPDATE_START: null,
  CART_ITEM_UPDATE_COMPLETE: null,
  CART_ITEM_UPDATE_FAIL: null,

  CART_ITEM_DELETE_START: null,
  CART_ITEM_DELETE_COMPLETE: null,
  CART_ITEM_DELETE_FAIL: null,
})