cache:
  yarn: true
  directories:
    - node_modules

language: node_js

node_js:
  - "iojs"
  - "7"

install:
    - yarn install

build:
    - node scripts/test.js --env=jsdom --coverage --coverageReporters=text-lcov |  ./node_modules/coveralls/bin/coveralls.js

