cache:
  yarn: true
  directories:
    - node_modules

language: node_js

install:
    - yarn install

build:
    - yarn test --coverage --coverageReporters=text-lcov |  ./node_modules/coveralls/bin/coveralls.js

