import keyMirror from 'keymirror'

export default keyMirror({
  SPONSORSHIP_INDEX_START: null,
  SPONSORSHIP_INDEX_COMPLETE: null,
  SPONSORSHIP_INDEX_FAIL: null,

  SPONSORSHIP_CREATE_START: null,
  SPONSORSHIP_CREATE_COMPLETE: null,
  SPONSORSHIP_CREATE_FAIL: null,

  SPONSORSHIP_SHOW_START: null,
  SPONSORSHIP_SHOW_COMPLETE: null,
  SPONSORSHIP_SHOW_FAIL: null,

  SPONSORSHIP_UPDATE_START: null,
  SPONSORSHIP_UPDATE_COMPLETE: null,
  SPONSORSHIP_UPDATE_FAIL: null,

  SPONSORSHIP_DELETE_START: null,
  SPONSORSHIP_DELETE_COMPLETE: null,
  SPONSORSHIP_DELETE_FAIL: null,

  SPONSORSHIP_COMMENT_UPDATE_START: null,
  SPONSORSHIP_COMMENT_UPDATE_COMPLETE: null,
  SPONSORSHIP_COMMENT_UPDATE_FAIL: null,

  SPONSORSHIP_OFFER_INDEX_START: null,
  SPONSORSHIP_OFFER_INDEX_COMPLETE: null,
  SPONSORSHIP_OFFER_INDEX_FAIL: null,

  SPONSORSHIP_OFFER_CREATE_START: null,
  SPONSORSHIP_OFFER_CREATE_COMPLETE: null,
  SPONSORSHIP_OFFER_CREATE_FAIL: null,

  SPONSORSHIP_OFFER_SHOW_START: null,
  SPONSORSHIP_OFFER_SHOW_COMPLETE: null,
  SPONSORSHIP_OFFER_SHOW_FAIL: null,

  SPONSORSHIP_OFFER_UPDATE_START: null,
  SPONSORSHIP_OFFER_UPDATE_COMPLETE: null,
  SPONSORSHIP_OFFER_UPDATE_FAIL: null,

  SPONSORSHIP_OFFER_DELETE_START: null,
  SPONSORSHIP_OFFER_DELETE_COMPLETE: null,
  SPONSORSHIP_OFFER_DELETE_FAIL: null,

  SPONSORSHIP_OFFER_COMMENT_UPDATE_START: null,
  SPONSORSHIP_OFFER_COMMENT_UPDATE_COMPLETE: null,
  SPONSORSHIP_OFFER_COMMENT_UPDATE_FAIL: null,

  SPONSORSHIP_OFFER_ITEM_INDEX_START: null,
  SPONSORSHIP_OFFER_ITEM_INDEX_COMPLETE: null,
  SPONSORSHIP_OFFER_ITEM_INDEX_FAIL: null,

  SPONSORSHIP_OFFER_ITEM_CREATE_START: null,
  SPONSORSHIP_OFFER_ITEM_CREATE_COMPLETE: null,
  SPONSORSHIP_OFFER_ITEM_CREATE_FAIL: null,

  SPONSORSHIP_OFFER_ITEM_SHOW_START: null,
  SPONSORSHIP_OFFER_ITEM_SHOW_COMPLETE: null,
  SPONSORSHIP_OFFER_ITEM_SHOW_FAIL: null,

  SPONSORSHIP_OFFER_ITEM_UPDATE_START: null,
  SPONSORSHIP_OFFER_ITEM_UPDATE_COMPLETE: null,
  SPONSORSHIP_OFFER_ITEM_UPDATE_FAIL: null,

  SPONSORSHIP_OFFER_ITEM_DELETE_START: null,
  SPONSORSHIP_OFFER_ITEM_DELETE_COMPLETE: null,
  SPONSORSHIP_OFFER_ITEM_DELETE_FAIL: null,

  SPONSORSHIP_OFFER_ITEM_COMMENT_UPDATE_START: null,
  SPONSORSHIP_OFFER_ITEM_COMMENT_UPDATE_COMPLETE: null,
  SPONSORSHIP_OFFER_ITEM_COMMENT_UPDATE_FAIL: null,
})