import keyMirror from 'keymirror'

export default keyMirror({
  PRESENTATION_INDEX_START: null,
  PRESENTATION_INDEX_COMPLETE: null,
  PRESENTATION_INDEX_FAIL: null,

  PRESENTATION_CREATE_START: null,
  PRESENTATION_CREATE_COMPLETE: null,
  PRESENTATION_CREATE_FAIL: null,

  PRESENTATION_SHOW_START: null,
  PRESENTATION_SHOW_COMPLETE: null,
  PRESENTATION_SHOW_FAIL: null,

  PRESENTATION_UPDATE_START: null,
  PRESENTATION_UPDATE_COMPLETE: null,
  PRESENTATION_UPDATE_FAIL: null,

  PRESENTATION_DELETE_START: null,
  PRESENTATION_DELETE_COMPLETE: null,
  PRESENTATION_DELETE_FAIL: null,

  PRESENTATION_COMMENT_UPDATE_START: null,
  PRESENTATION_COMMENT_UPDATE_COMPLETE: null,
  PRESENTATION_COMMENT_UPDATE_FAIL: null,
})