import keyMirror from 'keymirror'

export default keyMirror({
  CATEGORY_INDEX_START: null,
  CATEGORY_INDEX_COMPLETE: null,
  CATEGORY_INDEX_FAIL: null,

  CATEGORY_CREATE_START: null,
  CATEGORY_CREATE_COMPLETE: null,
  CATEGORY_CREATE_FAIL: null,

  CATEGORY_UPDATE_START: null,
  CATEGORY_UPDATE_COMPLETE: null,
  CATEGORY_UDPATE_FAIL: null,

  CATEGORY_SHOW_START: null,
  CATEGORY_SHOW_COMPLETE: null,
  CATEGORY_SHOW_FAIL: null,

  CATEGORY_SUGGESTIONS_INDEX_START: null,
  CATEGORY_SUGGESTIONS_INDEX_COMPLETE: null,
  CATEGORY_SUGGESTIONS_INDEX_FAIL: null,

  CATEGORY_FOLLOW_CREATE_START: null,
  CATEGORY_FOLLOW_CREATE_COMPLETE: null,
  CATEGORY_FOLLOW_CREATE_FAIL: null,

  CATEGORY_FOLLOW_DELETE_START: null,
  CATEGORY_FOLLOW_DELETE_COMPLETE: null,
  CATEGORY_FOLLOW_DELETE_FAIL: null,

  CATEGORY_SLUG_VERIFY_START: null,
  CATEGORY_SLUG_VERIFY_COMPLETE: null,
  CATEGORY_SLUG_VERIFY_FAIL: null,

  CATEGORY_VIEWS_UPDATE_START: null,
  CATEGORY_VIEWS_UPDATE_COMPLETE: null,
  CATEGORY_VIEWS_UPDATE_FAIL: null,

  USER_CATEGORY_INDEX_START: null,
  USER_CATEGORY_INDEX_COMPLETE: null,
  USER_CATEGORY_INDEX_FAIL: null,
})
