export default {
  communities: [
    {
      id: 1,
      name: 'Facebook Developer Circle Lagos',
      description: 'A community of developers united in knowledge sharing.',
      featured_image: '/login-bg.jpg',
      no_of_members: 200,
      no_of_upcoming_events: 2,
      focus: 'Technology',
      joined: true,
    },
    {
      id: 2,
      name: 'Google Developer Group',
      description: 'Developer community bringing up community interest, powereed by google.',
      featured_image: '/tech_is_in_you.png',
      no_of_members: 200,
      no_of_upcoming_events: 2,
      focus: 'Developers',
      joined: true,
    },
    {
      id: 3,
      name: 'Facebook Developer Circle Lagos',
      description: 'A community of developers united in knowledge sharing',
      featured_image: '/login-bg.jpg',
      no_of_members: 200,
      no_of_upcoming_events: 2,
      focus: 'Technology',
      joined: true,
    },
  ],

  events: [
    {
      id: 1,
      title: 'Tech is in you',
      featured_image: '/tech_is_in_you.png',
      interested: true,
      interested_persons: 211,
      start_date: '28 June, 2018',
      start_time: '10:00am',
      end_date: '28 June, 2018',
      end_time: '01:00pm',
      venue: 'StartZone, Gbagada',
      community: {
        id: 3,
        name: 'Google Developer Group',
        description: 'Developer community bringing up community interest, powereed by google.',
        featured_image: '/login-bg.jpg',
        no_of_members: 200,
        no_of_upcoming_events: 2,
        focus: 'Developers',
        joined: false,
      }
    },
    {
      id: 2,
      title: 'Writers corner workshop',
      featured_image: '/login-bg.jpg',
      interested: true,
      interested_persons: 211,
      start_date: '28 June, 2018',
      start_time: '10:00am',
      end_date: '28 June, 2018',
      end_time: '01:00pm',
      venue: 'StartZone, Gbagada',
      community: {
        id: 1,
        name: 'GDG Lagos',
        description: 'A community of developers united in knowledge sharing',
        featured_image: '/tech_is_in_you.png',
        no_of_members: 200,
        no_of_upcoming_events: 2,
        focus: 'Technology',
        joined: false,
      }
    },
    {
      id: 3,
      title: 'Figma Design Series',
      featured_image: '/tech_is_in_you.png',
      interested: false,
      interested_persons: 108,
      start_date: '28 June, 2018',
      start_time: '10:00am',
      end_date: '28 June, 2018',
      end_time: '01:00pm',
      venue: 'StartZone, Gbagada',
      community: {
        id: 2,
        name: 'Facebook Developer Circle Lagos',
        description: 'A community of developers united in knowledge sharing',
        featured_image: '/tech_is_in_you.png',
        no_of_members: 200,
        no_of_upcoming_events: 2,
        focus: 'Technology',
        joined: false,
      }
    }
  ]
}