import keyMirror from 'keymirror'

export default keyMirror({
  RESOURCE_INDEX_START: null,
  RESOURCE_INDEX_COMPLETE: null,
  RESOURCE_INDEX_FAIL: null,

  RESOURCE_CREATE_START: null,
  RESOURCE_CREATE_COMPLETE: null,
  RESOURCE_CREATE_FAIL: null,

  RESOURCE_SHOW_START: null,
  RESOURCE_SHOW_COMPLETE: null,
  RESOURCE_SHOW_FAIL: null,

  RESOURCE_UPDATE_START: null,
  RESOURCE_UPDATE_COMPLETE: null,
  RESOURCE_UPDATE_FAIL: null,

  RESOURCE_DELETE_START: null,
  RESOURCE_DELETE_COMPLETE: null,
  RESOURCE_DELETE_FAIL: null,
})