export default {
  REQUEST_LEAD_START: 'REQUEST_LEAD_START',
  RECEIVE_LEAD_START: 'RECEIVE_LEAD_START',
  FAIL_LEAD_START: 'FAIL_LEAD_START',

  REQUEST_LEAD_UPDATE: 'REQUEST_LEAD_UPDATE',
  RECEIVE_LEAD_UPDATE: 'RECEIVE_LEAD_UPDATE',
  FAIL_LEAD_UPDATE: 'FAIL_LEAD_UPDATE',
}