import keyMirror from 'keymirror'

export default keyMirror({
  INVITATION_INDEX_START: null,
  INVITATION_INDEX_COMPLETE: null,
  INVITATION_INDEX_FAIL: null,

  INVITATION_CREATE_START: null,
  INVITATION_CREATE_COMPLETE: null,
  INVITATION_CREATE_FAIL: null,

  INVITATION_UPDATE_START: null,
  INVITATION_UPDATE_COMPLETE: null,
  INVITATION_UPDATE_FAIL: null,

  INVITATION_USER_PENDING_INDEX_START: null,
  INVITATION_USER_PENDING_INDEX_COMPLETE: null,
  INVITATION_USER_PENDING_INDEX_FAIL: null,

  INVITATION_USER_PENDING_UPDATE_START: null,
  INVITATION_USER_PENDING_UPDATE_COMPLETE: null,
  INVITATION_USER_PENDING_UPDATE_FAIL: null,
})