import keyMirror from 'keymirror'

export default keyMirror({
  CHECK_IN_START: null,
  CHECK_IN_COMPLETE: null,
  CHECK_IN_FAIL: null,

  GUEST_SHOW_START: null,
  GUEST_SHOW_COMPLETE: null,
  GUEST_SHOW_FAIL: null,

  GUEST_UPDATE_START: null,
  GUEST_UPDATE_COMPLETE: null,
  GUEST_UPDATE_FAIL: null,

  GUEST_BATCH_UPDATE_START: null,
  GUEST_BATCH_UPDATE_COMPLETE: null,
  GUEST_BATCH_UPDATE_FAIL: null,

  GUEST_INDEX_START: null,
  GUEST_INDEX_COMPLETE: null,
  GUEST_INDEX_FAIL: null,

  GUEST_DELETE_START: null,
  GUEST_DELETE_COMPLETE: null,
  GUEST_DELETE_FAIL: null,
})