import keyMirror from 'keymirror'

export default keyMirror({
  CHECK_IN_START: null,
  CHECK_IN_COMPLETE: null,
  CHECK_IN_FAIL: null,

  EVENT_FEEDBACK_CREATE_START: null,
  EVENT_FEEDBACK_CREATE_COMPLETE: null,
  EVENT_FEEDBACK_CREATE_FAIL: null,

  EVENT_FEEDBACK_RESPONSE_INDEX_START: null,
  EVENT_FEEDBACK_RESPONSE_INDEX_COMPLETE: null,
  EVENT_FEEDBACK_RESPONSE_INDEX_FAIL: null,

  FEEDBACK_REPORT_SHOW_START: null,
  FEEDBACK_REPORT_SHOW_COMPLETE: null,
  FEEDBACK_REPORT_SHOW_FAIL: null,

  FEEDBACK_REPORT_UPDATE_START: null,
  FEEDBACK_REPORT_UPDATE_COMPLETE: null,
  FEEDBACK_REPORT_UPDATE_FAIL: null,
})