import keyMirror from 'keymirror'

export default keyMirror({
  EVENT_INDEX_START: null,
  EVENT_INDEX_COMPLETE: null,
  EVENT_INDEX_FAIL: null,

  EVENT_SHOW_START: null,
  EVENT_SHOW_COMPLETE: null,
  EVENT_SHOW_FAIL: null,

  EVENT_CREATE_START: null,
  EVENT_CREATE_COMPLETE: null,
  EVENT_CREATE_FAIL: null,

  EVENT_UPDATE_START: null,
  EVENT_UPDATE_COMPLETE: null,
  EVENT_UPDATE_FAIL: null,

  EVENT_PAST_INDEX_START: null,
  EVENT_PAST_INDEX_COMPLETE: null,
  EVENT_PAST_INDEX_FAIL: null,

  EVENT_SUGGESTIONS_INDEX_START: null,
  EVENT_SUGGESTIONS_INDEX_COMPLETE: null,
  EVENT_SUGGESTIONS_INDEX_FAIL: null,

  EVENT_ATTEND_CREATE_START: null,
  EVENT_ATTEND_CREATE_COMPLETE: null,
  EVENT_ATTEND_CREATE_FAIL: null,

  EVENT_COMMENT_UPDATE_START: null,
  EVENT_COMMENT_UPDATE_COMPLETE: null,
  EVENT_COMMENT_UPDATE_FAIL: null,

  EVENT_COMMENT_INDEX_START: null,
  EVENT_COMMENT_INDEX_COMPLETE: null,
  EVENT_COMMENT_INDEX_FAIL: null,

  EVENT_ANNOUNCEMENT_INDEX_START: null,
  EVENT_ANNOUNCEMENT_INDEX_COMPLETE: null,
  EVENT_ANNOUNCEMENT_INDEX_FAIL: null,

  EVENT_ANNOUNCEMENT_UPDATE_START: null,
  EVENT_ANNOUNCEMENT_UPDATE_COMPLETE: null,
  EVENT_ANNOUNCEMENT_UPDATE_FAIL: null,

  EVENT_ORGANIZER_INVITATION_CREATE_START: null,
  EVENT_ORGANIZER_INVITATION_CREATE_COMPLETE: null,
  EVENT_ORGANIZER_INVITATION_CREATE_FAIL: null,

  EVENT_ORGANIZER_INVITATION_UPDATE_START: null,
  EVENT_ORGANIZER_INVITATION_UPDATE_COMPLETE: null,
  EVENT_ORGANIZER_INVITATION_UPDATE_FAIL: null,

  EVENT_ORGANIZER_INVITATION_DELETE_START: null,
  EVENT_ORGANIZER_INVITATION_DELETE_COMPLETE: null,
  EVENT_ORGANIZER_INVITATION_DELETE_FAIL: null,
})