import keyMirror from 'keymirror'

export default keyMirror({
  CHECK_IN_START: null,
  CHECK_IN_COMPLETE: null,
  CHECK_IN_FAIL: null,

  EVENT_ORGANIZER_UPDATE_START: null,
  EVENT_ORGANIZER_UPDATE_COMPLETE: null,
  EVENT_ORGANIZER_UPDATE_FAIL: null,

  EVENT_ORGANIZER_INVITATION_CREATE_START: null,
  EVENT_ORGANIZER_INVITATION_CREATE_COMPLETE: null,
  EVENT_ORGANIZER_INVITATION_CREATE_FAIL: null,

  EVENT_ORGANIZER_INVITATION_DELETE_START: null,
  EVENT_ORGANIZER_INVITATION_DELETE_COMPLETE: null,
  EVENT_ORGANIZER_INVITATION_DELETE_FAIL: null,
})