import keyMirror from 'keymirror'

export default keyMirror({
  EVENT_CHECKLIST_INDEX_START: null,
  EVENT_CHECKLIST_INDEX_COMPLETE: null,
  EVENT_CHECKLIST_INDEX_FAIL: null,

  EVENT_CHECKLIST_CREATE_START: null,
  EVENT_CHECKLIST_CREATE_COMPLETE: null,
  EVENT_CHECKLIST_CREATE_FAIL: null,

  EVENT_CHECKLIST_UPDATE_START: null,
  EVENT_CHECKLIST_UPDATE_COMPLETE: null,
  EVENT_CHECKLIST_UPDATE_FAIL: null,

  EVENT_CHECKLIST_TODO_ITEM_INDEX_START: null,
  EVENT_CHECKLIST_TODO_ITEM_INDEX_COMPLETE: null,
  EVENT_CHECKLIST_TODO_ITEM_INDEX_FAIL: null,

  EVENT_CHECKLIST_TODO_ITEM_UPDATE_START: null,
  EVENT_CHECKLIST_TODO_ITEM_UPDATE_COMPLETE: null,
  EVENT_CHECKLIST_TODO_ITEM_UPDATE_FAIL: null,
})