import keyMirror from 'keymirror'

export default keyMirror({
  COMMUNITY_INDEX_START: null,
  COMMUNITY_INDEX_COMPLETE: null,
  COMMUNITY_INDEX_FAIL: null,

  COMMUNITY_CREATE_START: null,
  COMMUNITY_CREATE_COMPLETE: null,
  COMMUNITY_CREATE_FAIL: null,

  COMMUNITY_UPDATE_START: null,
  COMMUNITY_UPDATE_COMPLETE: null,
  COMMUNITY_UDPATE_FAIL: null,

  COMMUNITY_SHOW_START: null,
  COMMUNITY_SHOW_COMPLETE: null,
  COMMUNITY_SHOW_FAIL: null,

  COMMUNITY_SUGGESTIONS_INDEX_START: null,
  COMMUNITY_SUGGESTIONS_INDEX_COMPLETE: null,
  COMMUNITY_SUGGESTIONS_INDEX_FAIL: null,

  COMMUNITY_FOLLOW_CREATE_START: null,
  COMMUNITY_FOLLOW_CREATE_COMPLETE: null,
  COMMUNITY_FOLLOW_CREATE_FAIL: null,

  COMMUNITY_FOLLOW_DELETE_START: null,
  COMMUNITY_FOLLOW_DELETE_COMPLETE: null,
  COMMUNITY_FOLLOW_DELETE_FAIL: null,

  COMMUNITY_SLUG_VERIFY_START: null,
  COMMUNITY_SLUG_VERIFY_COMPLETE: null,
  COMMUNITY_SLUG_VERIFY_FAIL: null,

  COMMUNITY_VIEWS_UPDATE_START: null,
  COMMUNITY_VIEWS_UPDATE_COMPLETE: null,
  COMMUNITY_VIEWS_UDPATE_FAIL: null,
})
