import keyMirror from 'keymirror'

export default keyMirror({
  QUESTION_INDEX_START: null,
  QUESTION_INDEX_COMPLETE: null,
  QUESTION_INDEX_FAIL: null,

  QUESTION_CREATE_START: null,
  QUESTION_CREATE_COMPLETE: null,
  QUESTION_CREATE_FAIL: null,

  QUESTION_UPDATE_START: null,
  QUESTION_UPDATE_COMPLETE: null,
  QUESTION_UPDATE_FAIL: null,

  QUESTION_DELETE_START: null,
  QUESTION_DELETE_COMPLETE: null,
  QUESTION_DELETE_FAIL: null,
})