import keyMirror from 'keymirror'

export default keyMirror({
  PARTNER_INDEX_START: null,
  PARTNER_INDEX_COMPLETE: null,
  PARTNER_INDEX_FAIL: null,

  PARTNER_CREATE_START: null,
  PARTNER_CREATE_COMPLETE: null,
  PARTNER_CREATE_FAIL: null,

  PARTNER_SHOW_START: null,
  PARTNER_SHOW_COMPLETE: null,
  PARTNER_SHOW_FAIL: null,

  PARTNER_UPDATE_START: null,
  PARTNER_UPDATE_COMPLETE: null,
  PARTNER_UPDATE_FAIL: null,

  PARTNER_DELETE_START: null,
  PARTNER_DELETE_COMPLETE: null,
  PARTNER_DELETE_FAIL: null,

  PARTNER_COMMENT_UPDATE_START: null,
  PARTNER_COMMENT_UPDATE_COMPLETE: null,
  PARTNER_COMMENT_UPDATE_FAIL: null,
})