import keyMirror from 'keymirror'

export default keyMirror({
  EVENT_DISCUSSION_INDEX_START: null,
  EVENT_DISCUSSION_INDEX_COMPLETE: null,
  EVENT_DISCUSSION_INDEX_FAIL: null,

  EVENT_DISCUSSION_SHOW_START: null,
  EVENT_DISCUSSION_SHOW_COMPLETE: null,
  EVENT_DISCUSSION_SHOW_FAIL: null,

  EVENT_DISCUSSION_CREATE_START: null,
  EVENT_DISCUSSION_CREATE_COMPLETE: null,
  EVENT_DISCUSSION_CREATE_FAIL: null,

  EVENT_DISCUSSION_UPDATE_START: null,
  EVENT_DISCUSSION_UPDATE_COMPLETE: null,
  EVENT_DISCUSSION_UPDATE_FAIL: null,

  EVENT_DISCUSSION_COMMENT_INDEX_START: null,
  EVENT_DISCUSSION_COMMENT_INDEX_COMPLETE: null,
  EVENT_DISCUSSION_COMMENT_INDEX_FAIL: null,

  EVENT_DISCUSSION_COMMENT_CREATE_START: null,
  EVENT_DISCUSSION_COMMENT_CREATE_COMPLETE: null,
  EVENT_DISCUSSION_COMMENT_CREATE_FAIL: null,

  EVENT_DISCUSSION_COMMENT_UPDATE_START: null,
  EVENT_DISCUSSION_COMMENT_UPDATE_COMPLETE: null,
  EVENT_DISCUSSION_COMMENT_UPDATE_FAIL: null,
})