import keyMirror from 'keymirror'

export default keyMirror({
  TODO_ITEM_INDEX_START: null,
  TODO_ITEM_INDEX_COMPLETE: null,
  TODO_ITEM_INDEX_FAIL: null,

  TODO_ITEM_CREATE_START: null,
  TODO_ITEM_CREATE_COMPLETE: null,
  TODO_ITEM_CREATE_FAIL: null,

  TODO_ITEM_UPDATE_START: null,
  TODO_ITEM_UPDATE_COMPLETE: null,
  TODO_ITEM_UPDATE_FAIL: null,

  TODO_ITEM_DELETE_START: null,
  TODO_ITEM_DELETE_COMPLETE: null,
  TODO_ITEM_DELETE_FAIL: null,

  TODO_ITEM_COMMENT_CREATE_START: null,
  TODO_ITEM_COMMENT_CREATE_COMPLETE: null,
  TODO_ITEM_COMMENT_CREATE_FAIL: null,

  TODO_ITEM_COMMENT_UPDATE_START: null,
  TODO_ITEM_COMMENT_UPDATE_COMPLETE: null,
  TODO_ITEM_COMMENT_UPDATE_FAIL: null,
})